[build]
  publish = "_site"
  command = "npm run build"

# Redirect Netlify subdomain
[[redirects]]
  from = "https://a11yme.netlify.app/*"
  to = "https://a11y.me"
  status = 301
  force = true

[[redirects]]
  from = "http://a11yme.netlify.app/*"
  to = "https://a11y.me"
  status = 301
  force = true

[[redirects]]
  from = "https://www.a11yme.netlify.app/*"
  to = "https://a11y.me"
  status = 301
  force = true

[[redirects]]
  from = "http://www.a11yme.netlify.app/*"
  to = "https://a11y.me"
  status = 301
  force = true

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self'; img-src 'self'; style-src 'self' 'unsafe-inline'; font-src 'self'; script-src 'self'; connect-src 'self'; worker-src 'self'; manifest-src 'self'; media-src 'self'; object-src 'none'; frame-src 'none'; frame-ancestors 'none';"
    Permissions-Policy = '''
      accelerometer=(),
      ambient-light-sensor=(),
      autoplay=(),
      camera=(),
      encrypted-media=(),
      fullscreen=(),
      geolocation=(),
      gyroscope=(),
      magnetometer=(),
      microphone=(),
      midi=(),
      payment=(),
      picture-in-picture=(),
      speaker=(),
      usb=(),
      vibrate=(),
      vr=()
    '''
    Referrer-Policy = "strict-origin-when-cross-origin"
    Strict-Transport-Security = "max-age=2592000"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "deny"
    X-XSS-Protection = "1; mode=block"
